<?php

namespace Fabdepsys\Process\Validator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-21 at 14:04:27.
 */
class BuildTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Build
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Build;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    public function testValid() {
        $params = array(
            'project_id' => 'val1',
            'remote_address' => 'val1',
            'process' => 'val1',
            'status' => 'val1',
            'details' => array(
                'url' => 'val1',
                'repository' => 'val1',
                'jenkins_project' => 'val1',
                'jenkins_jobname' => 'val1',
                'jenkins_token' => 'val1'
            )
        );
        $this->object->setParams($params);
        $this->assertTrue($this->object->valid());
    }

    public function testFieldChecker() {
        $ret = $this->object->fieldChecker(
                array(
                    'test'
                ),
                array(
                    'a' => '1',
                    'test' => 'val1'
                )
        );
        $this->assertTrue($ret);
    }

}
