<?php
namespace Fabdepsys\Process\Validator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-21 at 15:59:16.
 */
class TestBuild extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Build
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Build;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
