<?php

namespace Fabdepsys\Project\Service;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-19 at 09:57:19.
 */
class ApiTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Api
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Api;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Fabdepsys\Project\Service\Api::setRequest
     * @todo   Implement testSetRequest().
     */
//    public function testSetRequest() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }

    /**
     * @covers Fabdepsys\Project\Service\Api::init
     * @todo   Implement testInit().
     */
//    public function testInit() {
//        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
//    }
    
    public function testTest(){
        
        $this->assertTrue(is_array($this->object->test()));
    }

}
